name: Build IPA

on:
  push:
    branches: [ "iOS" ]
  pull_request:
    branches: [ "iOS" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Ensure the runner uses a new enough Xcode version
      - name: Set Xcode Version
        run: |
          sudo xcode-select -s /Applications/Xcode_14.3.app/Contents/Developer
          xcodebuild -version

      # Capture the default scheme from the project
      - name: Set Default Scheme
        id: set_scheme
        run: |
          # List schemes in JSON and pick the first scheme
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo "$scheme_list" | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['schemes'][0]")
          echo "default=${default}" >> $GITHUB_ENV
          echo "Using default scheme: ${default}"

      - name: Build
        env:
          scheme: ${{ env.default }}
        run: |
          # Build for a generic iOS device
          xcodebuild clean archive \
            -scheme "$scheme" \
            -configuration Release \
            -archivePath "$PWD/build/${scheme}.xcarchive" \
            -sdk iphoneos \
            -allowProvisioningUpdates \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

          # Create IPA
          mkdir Payload
          # Adjust the app name if needed (ensure it matches your built product)
          cp -r build/${scheme}.xcarchive/Products/Applications/Countdown.app Payload/
          zip -r "${scheme}.ipa" Payload
          rm -rf Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.default }}.ipa"
          path: "${{ env.default }}.ipa"
          retention-days: 90
