name: Build IPA

on:
  push:
    branches: [ "iOS" ]
  pull_request:
    branches: [ "iOS" ]

jobs:
  build:
    name: Build IPA for StikNES
    runs-on: macos-latest  # Changed from macos-15 to macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install Dependencies
        run: |
          gem install xcpretty
          brew install ldid

      - name: Build IPA
        env:
          SCHEME: "StikNES"
        run: |
          echo "🚀 Building scheme: $SCHEME"

          # Create build directory
          mkdir -p build

          # Build for iOS
          xcodebuild clean archive \
            -project StikNES.xcodeproj \
            -scheme "$SCHEME" \
            -configuration Release \
            -archivePath "build/$SCHEME.xcarchive" \
            -destination 'generic/platform=iOS' \
            -allowProvisioningUpdates \
            CODE_SIGN_IDENTITY=- \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO | xcpretty

          # Create Payload directory
          mkdir -p Payload
          cp -r "build/$SCHEME.xcarchive/Products/Applications/$SCHEME.app" Payload/

          # Create IPA
          zip -r "build/$SCHEME.ipa" Payload
          rm -rf Payload

          # Verify IPA exists
          if [ ! -f "build/$SCHEME.ipa" ]; then
            echo "❌ Error: IPA file not found!"
            exit 1
          fi
          echo "✅ IPA successfully created: build/$SCHEME.ipa"

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: StikNES.ipa
          path: build/StikNES.ipa
          retention-days: 90

      - name: Upload Build Logs (if failed)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: xcode-logs
          path: ~/Library/Developer/Xcode/DerivedData/**/Logs/Build
          retention-days: 7