name: Build IPA

on:
  push:
    branches: [ "iOS" ]
  pull_request:
    branches: [ "iOS" ]

jobs:
  build:
    name: Build IPA for StikNES
    runs-on: macos-15  # Updated to macOS 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Xcode 16
        run: |
          # Look for Xcode 16 with possible minor version variations
          XCODE_PATH=$(ls -d /Applications/Xcode_16* | head -n 1)
          if [ -z "$XCODE_PATH" ]; then
            echo "Xcode 16 not found! Listing available versions:"
            ls -l /Applications | grep Xcode
            exit 1
          fi
          sudo xcode-select -s "$XCODE_PATH/Contents/Developer"
          echo "Using Xcode at: $XCODE_PATH"
          xcodebuild -version

      - name: Build IPA
        env:
          SCHEME: "StikNES"
        run: |
          echo "Building scheme: $SCHEME"
          
          # Create build directory
          mkdir -p build

          # Clean and archive the project
          xcodebuild clean archive \
            -scheme "$SCHEME" \
            -configuration Release \
            -archivePath "$PWD/build/${SCHEME}.xcarchive" \
            -sdk iphoneos \
            -allowProvisioningUpdates \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

          # Export IPA from archive
          xcodebuild -exportArchive \
            -archivePath "$PWD/build/${SCHEME}.xcarchive" \
            -exportOptionsPlist <(echo '{ "method": "ad-hoc", "signingStyle": "manual", "signingCertificate": "", "teamID": "" }') \
            -exportPath "$PWD/build"

          # Ensure the IPA exists
          if [ ! -f "build/${SCHEME}.ipa" ]; then
            echo "Error: IPA file not found!"
            exit 1
          fi

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: StikNES.ipa
          path: build/StikNES.ipa
          retention-days: 90
