name: Build IPA

on:
  push:
    branches: [ "iOS" ]
  pull_request:
    branches: [ "iOS" ]

jobs:
  build:
    name: Build IPA for StikNES
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print Xcode Version and List Installations
        run: |
          echo "Using Xcode version:"
          xcodebuild -version
          echo "Listing available Xcode installations:"
          ls /Applications | grep Xcode

      - name: Set Xcode Version
        run: |
          # Use the default Xcode installation available on the runner.
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
          xcodebuild -version

      - name: Build
        env:
          scheme: "StikNES"
        run: |
          echo "Building scheme: $scheme"
          # Clean and archive the project for a generic iOS device
          xcodebuild clean archive \
            -scheme "$scheme" \
            -configuration Release \
            -archivePath "$PWD/build/${scheme}.xcarchive" \
            -sdk iphoneos \
            -allowProvisioningUpdates \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

          # Package the built app into an IPA
          mkdir Payload
          cp -r build/${scheme}.xcarchive/Products/Applications/${scheme}.app Payload/
          zip -r "${scheme}.ipa" Payload
          rm -rf Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.scheme }}.ipa"
          path: "${{ env.scheme }}.ipa"
          retention-days: 90
