name: Build IPA

on:
  push:
    branches: [ "iOS" ]
  pull_request:
    branches: [ "iOS" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Xcode Version
        run: |
          # Use the default Xcode installation available on the runner.
          # Note: If your project requires a newer Xcode version (e.g. Xcode 15) you'll need a runner with that version.
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
          xcodebuild -version

      - name: List available Xcode installations
        run: ls /Applications | grep Xcode

      - name: List schemes in JSON (diagnostic)
        run: |
          # This command may fail if the project file format is newer than supported.
          echo "Attempting to list schemes from the project..."
          xcodebuild -list -json || echo "Failed to list schemes. Your project may use a newer Xcode file format."

      - name: Set Default Scheme
        id: set_scheme
        run: |
          # Attempt to capture the list of schemes. If xcodebuild fails to read the project,
          # this step will exit with an error.
          scheme_list=$(xcodebuild -list -json 2>/dev/null | tr -d "\n")
          if [ -z "$scheme_list" ]; then
            echo "Error: Unable to retrieve schemes. Ensure your project file format is compatible with the runner's Xcode."
            exit 1
          fi
          default=$(echo "$scheme_list" | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['schemes'][0]")
          echo "default=${default}" >> $GITHUB_ENV
          echo "Using default scheme: ${default}"

      - name: Build
        env:
          scheme: ${{ env.default }}
        run: |
          # Clean and archive the project for a generic iOS device
          xcodebuild clean archive \
            -scheme "$scheme" \
            -configuration Release \
            -archivePath "$PWD/build/${scheme}.xcarchive" \
            -sdk iphoneos \
            -allowProvisioningUpdates \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

          # Package the built app into an IPA
          mkdir Payload
          # IMPORTANT: Adjust "Countdown.app" if your app’s product name differs.
          cp -r build/${scheme}.xcarchive/Products/Applications/Countdown.app Payload/
          zip -r "${scheme}.ipa" Payload
          rm -rf Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.default }}.ipa"
          path: "${{ env.default }}.ipa"
          retention-days: 90
