name: Build IPA

on:
  push:
    branches: [ "iOS" ]
  pull_request:
    branches: [ "iOS" ]

jobs:
  build:
    name: Build IPA for StikNES
    runs-on: macos-15  # Updated to macOS 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Xcode 16
        run: |
          # Look for Xcode 16 with possible minor version variations
          XCODE_PATH=$(ls -d /Applications/Xcode_16* | head -n 1)
          if [ -z "$XCODE_PATH" ]; then
            echo "Xcode 16 not found! Listing available versions:"
            ls -l /Applications | grep Xcode
            exit 1
          fi
          sudo xcode-select -s "$XCODE_PATH/Contents/Developer"
          echo "Using Xcode at: $XCODE_PATH"
          xcodebuild -version

      - name: Build IPA
        env:
          SCHEME: "StikNES"
        run: |
          echo "Building scheme: $SCHEME"
          
          # Create build directory
          mkdir -p build
          
          # Clean and archive the project
          xcodebuild clean archive \
            -scheme "$SCHEME" \
            -configuration Release \
            -archivePath "$PWD/build/${SCHEME}.xcarchive" \
            -sdk iphoneos \
            -allowProvisioningUpdates \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

          # Create IPA
          mkdir Payload
          cp -r "build/${SCHEME}.xcarchive/Products/Applications/${SCHEME}.app" Payload/
          zip -r "${SCHEME}.ipa" Payload
          
          # Cleanup
          rm -rf Payload build/${SCHEME}.xcarchive

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.SCHEME }}.ipa"
          path: "${{ env.SCHEME }}.ipa"
          retention-days: 90
